run:
  timestamp: '20250908_111328'
  csv_path: C:\Users\sagni\Downloads\Cardio Track\archive\heart.csv
  out_dir: C:\Users\sagni\Downloads\Cardio Track
  target: target
preprocessing:
  numeric_columns:
  - age
  - sex
  - cp
  - trestbps
  - chol
  - fbs
  - restecg
  - thalach
  - exang
  - oldpeak
  - slope
  - ca
  - thal
  categorical_columns: []
  impute_numeric: median
  impute_categorical: most_frequent
  scale_numeric: standard
  one_hot: true
models_tried:
- logreg
- rf
chosen_model: rf
